version: 2
before:
  hooks:
    - go mod download
builds:
  - id: migrate-to-smartsheet
    main: ./cmd/migrate/
    binary: migrate-to-smartsheet
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude: ["^docs:", "^test:", "^chore:"]
release:
  github:
    owner: glitchedgod
    name: migrate-to-smartsheet
