package postmigration

import (
	"fmt"
	"net/url"
	"os/exec"
	"regexp"
	"runtime"
	"strings"
)

// ── Anonymisation ─────────────────────────────────────────────────────────────

var (
	// reEmail matches standard email addresses.
	reEmail = regexp.MustCompile(`[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}`)

	// reToken matches long (20+ char) alphanumeric strings that look like API
	// keys, bearer tokens, or access tokens.  We require at least one digit and
	// one letter to avoid matching long all-alpha words (e.g. error messages).
	reToken = regexp.MustCompile(`\b(?:[a-zA-Z0-9_\-]{20,})\b`)

	// reURL matches http/https URLs that are NOT Smartsheet API or GitHub URLs
	// (those are safe / diagnostic and must be kept).
	reURL = regexp.MustCompile(`https?://[^\s"'<>]+`)
)

// safeURL returns true for URLs that should be kept verbatim in reports.
func safeURL(u string) bool {
	return strings.Contains(u, "smartsheet.com/api") ||
		strings.Contains(u, "github.com")
}

// looksLikeToken returns true when the string looks like an opaque token
// rather than a normal word or number (requires a mix of letters + digits or
// contains special token characters like underscores in typical positions).
func looksLikeToken(s string) bool {
	hasDigit := false
	hasLetter := false
	for _, r := range s {
		if r >= '0' && r <= '9' {
			hasDigit = true
		} else if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') {
			hasLetter = true
		}
		if hasDigit && hasLetter {
			return true
		}
	}
	// All-digit strings (e.g. error codes) should not be replaced.
	return false
}

// Anonymise applies the following replacements to raw in order:
//  1. Email addresses            → [email]
//  2. API tokens (20+ char alnum with mixed digit+letter) → [token]
//  3. Non-API, non-GitHub URLs   → [url]
//
// Safe diagnostics kept as-is: error codes, Smartsheet API error text, column
// type names, row/column counts, Go stack traces.
func Anonymise(raw string) string {
	// 1. Emails first (before URL regex could partially swallow them).
	s := reEmail.ReplaceAllString(raw, "[email]")

	// 2. Tokens — long alphanumeric strings that look like keys.
	s = reToken.ReplaceAllStringFunc(s, func(match string) string {
		if looksLikeToken(match) {
			return "[token]"
		}
		return match
	})

	// 3. URLs — only replace ones that aren't safe diagnostic URLs.
	s = reURL.ReplaceAllStringFunc(s, func(match string) string {
		if safeURL(match) {
			return match
		}
		return "[url]"
	})

	return s
}

// ── GitHub issue URL builder ───────────────────────────────────────────────────

const githubIssueBase = "https://github.com/glitchedgod/migrate-to-smartsheet/issues/new"

// BuildGitHubIssueURL constructs a pre-filled GitHub new-issue URL from the
// platform name and a slice of error strings.  Each error is anonymised before
// being embedded in the URL.
func BuildGitHubIssueURL(platform string, errors []string) string {
	// Build title from the first error snippet.
	titleSnippet := "unknown error"
	if len(errors) > 0 {
		snippet := Anonymise(errors[0])
		// Truncate to ~60 chars so the title stays readable.
		if len(snippet) > 60 {
			snippet = snippet[:57] + "..."
		}
		titleSnippet = snippet
	}
	title := fmt.Sprintf("Migration error: %s \u2192 %s", platform, titleSnippet)

	// Build body.
	var sb strings.Builder
	sb.WriteString("## Migration error report\n\n")
	sb.WriteString(fmt.Sprintf("**Platform:** %s\n\n", platform))

	if len(errors) > 0 {
		sb.WriteString("**Errors:**\n\n")
		for _, e := range errors {
			sb.WriteString(fmt.Sprintf("- %s\n", Anonymise(e)))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("**Steps to reproduce:**\n\n")
	sb.WriteString("<!-- Please describe what you were doing when this error occurred -->\n\n")
	sb.WriteString("1. \n\n")
	sb.WriteString("---\n")
	sb.WriteString("*Generated by migrate-to-smartsheet. Sensitive values have been redacted.*\n")

	params := url.Values{}
	params.Set("title", title)
	params.Set("body", sb.String())
	params.Set("labels", "bug")

	return githubIssueBase + "?" + params.Encode()
}

// ── Cross-platform browser opener ─────────────────────────────────────────────

// OpenBrowser opens url in the default system browser.
// Supports macOS (open), Linux (xdg-open), and Windows (start).
func OpenBrowser(rawURL string) error {
	var cmd *exec.Cmd
	switch runtime.GOOS {
	case "darwin":
		cmd = exec.Command("open", rawURL)
	case "linux":
		cmd = exec.Command("xdg-open", rawURL)
	case "windows":
		// "start" is a shell built-in; we must invoke it via cmd.exe.
		cmd = exec.Command("cmd", "/C", "start", rawURL)
	default:
		return fmt.Errorf("unsupported platform: %s", runtime.GOOS)
	}
	return cmd.Start()
}
